---
- hosts: localhost
  become: true
  vars:
    ql_web_user: qlweb
    ql_web_git_repository: https://github.com/pklaus/brother_ql_web.git
    ql_web_venv: "/home/{{ ql_web_user }}/.virtualenvs/ql"
    ql_web_working_path: "/home/{{ ql_web_user }}/{{ ql_web_git_repository | basename | splitext | first}}"
  handlers:
    - name: daemon reload
      command: systemctl daemon-reload
    - name: restart ql-web service
      systemd:
        name: brother-ql-web.service
        enabled: true
        state: restarted
  tasks:
    - user:
        name: "{{ ql_web_user }}"
        createhome: true
    - git:
        repo: "{{ ql_web_git_repository }}"
        dest: "{{ ql_web_working_path }}"
    - file:
        path: "{{ ql_web_working_path }}"
        owner: "{{ ql_web_user }}"
    - pip:
        virtualenv: "{{ ql_web_venv }}"
        virtualenv_python: /usr/bin/python3
        requirements: "{{ ql_web_working_path }}/requirements.txt"
    - template:
        src: brother-ql-web.service.j2
        dest: /etc/systemd/system/brother-ql-web.service
      notify:
        - daemon reload
        - restart ql-web service
